# http://www.cyberciti.biz/tips/bash-aliases-mac-centos-linux-unix.html

## Colorize the ls output ##
alias ls='ls -G'
## Use a long listing format ##
alias ll='ls -la'
## Show hidden files ##
alias l.='ls -d .* -G'
 
## Colorize the grep command output for ease of use (good for log files)##
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

## Start calculator with math support
alias bc='bc -l'

## For powerline status line
# References : http://blog.gtwang.org/linux/powerline-adds-powerful-statuslines-and-prompts-to-vim-and-bash/
which powerline-daemon &>/dev/null
if [ $? -eq 0 ]; then
  powerline-daemon -q
  POWERLINE_BASH_CONTINUATION=1
  POWERLINE_BASH_SELECT=1
  # Powerline installation directory can be retrieved via 'pip show powerline-status'
  POWERLINE_SCRIPT=/Library/Python/2.7/site-packages/powerline/bindings/bash/powerline.sh
  if [ -f $POWERLINE_SCRIPT ]; then
    source $POWERLINE_SCRIPT
  fi
fi

# Extra PATH settings
# [Extra tools under ~/.local/bin/]
# -----------------------------
export PATH=~/.local/bin:$PATH
# -----------------------------
#
